kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitlab
spec:
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: gitlab