---
providers:
  kubernetesCRD:
    namespaces:
      - default
      - traefik
      - k8seggjs
      - kubernetes-dashboard
      - flink-standalone-session
  kubernetesIngress:
    namespaces:
      - default
      - traefik
      - k8seggjs
      - kubernetes-dashboard
      - flink-standalone-session

ports:
  traefik:
    # expose: true
    nodePort: 32090
  web:
    nodePort: 32080
  websecure:
    nodePort: 32443
  cassandra:
    # expose: true
    port: 9042
    nodePort: 32091
  cassandrasecure:
    # expose: true
    port: 9142
    nodePort: 32092